// Internal package used by pau_top.sv and fpu_wrap.sv.
// All user-facing configuration lives in config_pkg.sv.
// Do not edit this file directly.

package ariane_pkg;
    import config_pkg::*;

    typedef struct packed {
         riscv::xlen_t       cause;
         riscv::xlen_t       tval;
         logic               valid;
    } exception_t;

    typedef enum logic [3:0] {
        NONE, LOAD, STORE, ALU, CTRL_FLOW, MULT, CSR, FPU, FPU_VEC, CVXIF, PAU
    } fu_t;

    typedef enum logic [7:0] {
        ADD, SUB, ADDW, SUBW, XORL, ORL, ANDL, SRA, SRL, SLL, SRLW, SLLW, SRAW,
        LTS, LTU, GES, GEU, EQ, NE, JALR, BRANCH, SLTS, SLTU,
        MRET, SRET, DRET, ECALL, WFI, FENCE, FENCE_I, SFENCE_VMA, CSR_WRITE, CSR_READ, CSR_SET, CSR_CLEAR,
        LD, SD, LW, LWU, SW, LH, LHU, SH, LB, SB, LBU,
        AMO_LRW, AMO_LRD, AMO_SCW, AMO_SCD, AMO_SWAPW, AMO_ADDW, AMO_ANDW, AMO_ORW, AMO_XORW, AMO_MAXW, AMO_MAXWU, AMO_MINW, AMO_MINWU,
        AMO_SWAPD, AMO_ADDD, AMO_ANDD, AMO_ORD, AMO_XORD, AMO_MAXD, AMO_MAXDU, AMO_MIND, AMO_MINDU,
        MUL, MULH, MULHU, MULHSU, MULW, DIV, DIVU, DIVW, DIVUW, REM, REMU, REMW, REMUW,
        FLD, FLW, FLH, FLB, FSD, FSW, FSH, FSB,
        FADD, FSUB, FMUL, FDIV, FMIN_MAX, FSQRT, FMADD, FMSUB, FNMSUB, FNMADD,
        FCVT_F2I, FCVT_I2F, FCVT_F2F, FSGNJ, FMV_F2X, FMV_X2F, FCMP, FCLASS,
        VFMIN, VFMAX, VFSGNJ, VFSGNJN, VFSGNJX, VFEQ, VFNE, VFLT, VFGE, VFLE, VFGT, VFCPKAB_S, VFCPKCD_S, VFCPKAB_D, VFCPKCD_D,
        OFFLOAD,
        PADD, PSUB, PMUL, PDIV, PSQRT, PMIN, PMAX,
        QMADD, QMSUB, QCLR, QNEG, QROUND,
        PCVT_P2I, PCVT_P2L, PCVT_P2U, PCVT_P2LU, PCVT_I2P, PCVT_L2P, PCVT_U2P, PCVT_LU2P,
        PSGNJ, PSGNJN, PSGNJX, PMV_P2X, PMV_X2P, PEQ, PLT, PLE,
        PLD, PLW, QL, PSD, PSW, QS
    } fu_op;

    typedef struct packed {
        fu_t         fu;
        fu_op        operator;
        logic [63:0] operand_a;   // explicit width (= riscv::xlen_t for XLEN=64)
        logic [63:0] operand_b;
        logic [63:0] imm;
        logic [5:0]  trans_id;
    } fu_data_t;

    localparam TRANS_ID_BITS = 6;
    localparam bit RVD       = 1'b1;
    localparam bit RVF       = 1'b1;
    localparam bit XF16      = 1'b0;
    localparam bit XF16ALT   = 1'b0;
    localparam bit XF8       = 1'b0;
    localparam bit XFVEC     = 1'b0;
    localparam int unsigned LAT_COMP_FP32   = 2;
    localparam int unsigned LAT_COMP_FP64   = 3;
    localparam int unsigned LAT_COMP_FP16   = 1;
    localparam int unsigned LAT_COMP_FP16ALT = 1;
    localparam int unsigned LAT_COMP_FP8    = 1;
    localparam int unsigned LAT_DIVSQRT     = 2;
    localparam int unsigned LAT_NONCOMP     = 1;
    localparam int unsigned LAT_CONV        = 2;

    // Posit configuration — derived from config_pkg (user edits config_pkg.sv)
    localparam int unsigned POSLEN       = config_pkg::DATA_WIDTH;
    localparam int unsigned QUIRELEN     = config_pkg::QUIRE_BITS;
    localparam bit          QUIRE_PRESENT = config_pkg::QUIRE_ENABLE;
    localparam bit          POS_LOG_MULT  = config_pkg::APPROX_MUL;
    localparam bit          POS_LOG_DIV   = config_pkg::APPROX_DIV;
    localparam bit          POS_LOG_SQRT  = config_pkg::APPROX_SQRT;
    localparam bit          POS_PRESENT   = (config_pkg::ACCEL_TYPE == "PAU");
    localparam bit          FP_PRESENT    = (config_pkg::ACCEL_TYPE == "FPU");
    localparam int unsigned FLEN          = 64;  // FPU always uses 64-bit containers

endpackage
