## Timing Constraints for PERCIVAL Accelerator (Zynq PS7 Design)
## Target: Xilinx Zedboard (Zynq-7000 xc7z020clg484-1)
##
## Clock constraints:
##   - PS7 FCLK_CLK0 (100 MHz): auto-generated by processing_system7 IP
##   - Clocking Wizard output (configurable): auto-generated by clk_wiz IP
##   - No external clock pins (clock comes from Zynq PS)
##
## I/O constraints:
##   - No PL-side I/O pins (all communication via PS7 M_AXI_GP0)
##   - DDR and FIXED_IO constraints handled by PS7 IP

## GCLK pin (zynq_accel_top impl flow only; harmless warning in accel_harness synth)
## Zedboard 100 MHz oscillator -> clk_wiz_0 MMCM -> clk_core + clk_bram (2x).
set_property PACKAGE_PIN Y9        [get_ports {GCLK}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GCLK}]
create_clock -period 10.0 -name GCLK [get_ports {GCLK}]

## Clock Domain Crossing
## Both flows use clk_wiz_0: 100 MHz crystal -> CLKOUT1 (core+AXI) + CLKOUT2 (2x BRAM).
## In zynq_accel_top: M_AXI_GP0/GP1_ACLK = CLKOUT1 = accel_axi clk_i -> no CDC on AXI bus.

## Additional Timing Exceptions

## Step B: DBRAM -> arith_unit multicycle path constraint
## data_mem_reg* is clocked at clk_bram (2x clk_i). The path from the BRAM
## output registers (op_a_q / op_b_q, captured at clk_bram phase 1) to arith_unit
## inputs has a full clk_i period to settle (7.5 ns at 100 MHz arith / 200 MHz BRAM).
## Without this constraint Vivado applies a 5 ns (clk_bram) setup budget.
set_multicycle_path -setup 2 -from [get_cells {u_core/data_mem_reg*}] \
    -to [get_cells -filter {IS_SEQUENTIAL} {u_core/u_arith/*}]
set_multicycle_path -hold 1 -from [get_cells {u_core/data_mem_reg*}] \
    -to [get_cells -filter {IS_SEQUENTIAL} {u_core/u_arith/*}]
