## Timing Constraints for PERCIVAL Accelerator (Zynq PS7 Design)
## Target: Xilinx Zedboard (Zynq-7000 xc7z020clg484-1)
##
## Clock constraints:
##   - PS7 FCLK_CLK0 (100 MHz): auto-generated by processing_system7 IP
##   - Clocking Wizard output (configurable): auto-generated by clk_wiz IP
##   - No external clock pins (clock comes from Zynq PS)
##
## I/O constraints:
##   - No PL-side I/O pins (all communication via PS7 M_AXI_GP0)
##   - DDR and FIXED_IO constraints handled by PS7 IP

## GCLK pin (zynq_accel_top impl flow only; harmless warning in accel_harness synth)
## Zedboard 100 MHz oscillator -> clk_wiz_0 MMCM -> clk_core + clk_bram (2x).
set_property PACKAGE_PIN Y9        [get_ports {GCLK}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GCLK}]
create_clock -period 10.0 -name GCLK [get_ports {GCLK}]

## Clock Domain Crossing
## Both flows use clk_wiz_0: 100 MHz crystal -> CLKOUT1 (core+AXI) + CLKOUT2 (2x BRAM).
## In zynq_accel_top: M_AXI_GP0/GP1_ACLK = CLKOUT1 = accel_axi clk_i -> no CDC on AXI bus.

## Additional Timing Exceptions

## DBRAM operand CDC: op_a_q/op_b_q/fwd_q are clk_bram FFs (phase 1, T/2 before
## the next clk_i edge). Their T/2 window is too narrow for the 29 ns PAU path.
## op_a_wr_q/op_b_wr_q/fwd_wr_q (accel_core.sv) are clk_i FFs that re-sample
## these on the rising clk_i edge that starts each EX cycle. By that edge,
## op_a_q already holds the current instruction's operand (BRAM read completed
## at clk_bram phase 1 of the preceding ID cycle). So op_a_wr_q.Q is immediately
## valid with no pipeline latency added. The op_{a,b}_wr_q -> u_arith/* paths
## are clk_i -> clk_i with a full T budget and need no timing exception.
