## Timing Constraints for PERCIVAL Accelerator (Zynq PS7 Design)
## Target: Xilinx Zedboard (Zynq-7000 xc7z020clg484-1)
##
## Clock constraints:
##   - PS7 FCLK_CLK0 (100 MHz): auto-generated by processing_system7 IP
##   - Clocking Wizard output (configurable): auto-generated by clk_wiz IP
##   - No external clock pins (clock comes from Zynq PS)
##
## I/O constraints:
##   - No PL-side I/O pins (all communication via PS7 M_AXI_GP0)
##   - DDR and FIXED_IO constraints handled by PS7 IP

## Clock Domain Crossing
## The impl flow (zynq_accel_top) uses a single clock domain (FCLK_CLK0).
## The build flow (accel_harness) has clk_wiz_0 which may run at a different
## frequency; its constraints are handled in run_build.tcl.

## Additional Timing Exceptions
## Add project-specific false paths or multicycle paths below as needed
