## Timing Constraints for PAU FPU Harness (Zynq PS7 Design)
## Target: Xilinx Zedboard (Zynq-7000 xc7z020clg484-1)
##
## Clock constraints:
##   - PS7 FCLK_CLK0 (100 MHz): auto-generated by processing_system7 IP
##   - Clocking Wizard output (configurable): auto-generated by clk_wiz IP
##   - No external clock pins (clock comes from Zynq PS)
##
## I/O constraints:
##   - No PL-side I/O pins (all communication via PS7 M_AXI_GP0)
##   - DDR and FIXED_IO constraints handled by PS7 IP

## Clock Domain Crossing
## The clocking wizard output (clk_research) may differ from FCLK_CLK0.
## When both clocks run at the same frequency (default 100 MHz), they are
## phase-aligned and no CDC issues arise. For different frequencies,
## the AXI register interface (FCLK_CLK0 domain) and PAU/FPU compute
## path (clk_research domain) cross clock domains through the registered
## interfaces in pau_fpu_harness.
##
## Set async clock groups when running at non-default frequencies:
set_clock_groups -asynchronous \
    -group [get_clocks -of_objects [get_pins zynq_ps_i/ps7/inst/PS7_i/FCLKCLK[0]]] \
    -group [get_clocks -of_objects [get_pins zynq_ps_i/pau_axi/i_harness/i_clk_wiz/inst/mmcm_adv_inst/CLKOUT0]]

## Additional Timing Exceptions
## Add project-specific false paths or multicycle paths below as needed
